export const MODULES = {
  //  authentication Modules
  USER: "USER",
  ROLE: "ROLE",
  PERMISSION: "PERMISSION",
  TENANT: "TENANT",
  SUBSCRIPTION_PLAN : "SUBSCRIPTION_PLAN",
  PROJECT : "PROJECT",
  PAYMENT_LEDGER : "PAYMENT_LEDGER",
  PROJET_TASK : "PROJET_TASK",
  BANK_BRIEF : "BANK_BRIEF",

};
