export const MODULES = {
  //  authentication Modules & Sass Modules
  USER: "USER",
  ROLE: "ROLE",
  PERMISSION: "PERMISSION",
  TENANT: "TENANT",
  SUBSCRIPTION_PLAN : "SUBSCRIPTION_PLAN",
  PROJECT : "PROJECT",
  PROJECT_ESTIMATION : "PROJECT_ESTIMATION",
  PROJECT_UPDATE : "PROJECT_UPDATE",
  PROJECT_STAGE : "PROJECT_STAGE",
  PAYMENT_LEDGER : "PAYMENT_LEDGER",
  PROJET_TASK : "PROJET_TASK",
  BANK_BRIEF : "BANK_BRIEF",


  // Project Moduels

  CLIENT : "CLIENT",
  PROJECT : "PROJECT",
  TASK : "TASK",
  WORKER : "WORKER",
  WORKERTASK : "WORKERTASK",
  PAYMENT : "PAYMENT",
  ATTENDENCE : "ATTENDENCE",
 
};
