import Client from "../models/client.model.js";
import { generatePassword } from "../utils/autogeneratedpassword.js";
import bcrypt from "bcryptjs";

// export const createClient = async (data, tenantId) => {
//   return await Client.create({ ...data, tenantId });
// };
export const getClient = async (queryParams, tenantId) => {
  let filter = {
    tenantId: tenantId, // ✅ IMPORTANT
  };

  if (queryParams.clientName) {
    filter.clientName = {
      $regex: queryParams.clientName,
      $options: "i",
    };
  }
  if (queryParams.phone) {
    filter.phone = {
      $regex: queryParams.phone,
      $options: "i",
    };
  }
  if (queryParams.email) {
    filter.email = {
      $regex: queryParams.email,
      $options: "i",
    };
  }
  if (queryParams.address) {
    filter.address = {
      $regex: queryParams.address,
      $options: "i",
    };
  }

  const clients = await Client.find(filter).sort({ createdAt: -1 }).lean();

  return clients;
};
export const getClientbyId = async (id, tenantId) => {
  return await Client.findOne({
    _id: id,
    tenantId: tenantId,
  });

  //   .populate("tenantId")
};
export const updateClient = async (id, data, tenantId) => {
  return await Client.findOneAndUpdate({ _id: id, tenantId: tenantId }, data, {
    new: true,
  });
};
export const deleteClient = async (id, tenantId) => {
  return await Client.findByIdAndDelete({ _id: id, tenantId: tenantId });
};



export const createClient = async ({
  tenantId,
  roleId,
  email,
  clientName,
}) => {

  const plainPassword = generatePassword();

  const hashedPassword = await bcrypt.hash(plainPassword, 10);

  const user = await Client.create({
    tenantId,
    clientName,
    email,
    password: hashedPassword,
    role: roleId,
    isSuperAdmin: false,
  });

  return { user, plainPassword };
};