import { hasPassword } from "../utils/password.js";
import User from "../models/user.model.js";
import {
  generatePassword,
  generateUsername,
} from "../utils/autogeneratedpassword.js";
import bcrypt from "bcryptjs";
export const createUser = async (data, tenantId) => {
  if (!data.password) {
    throw new Error("Password is required");
  }

  data.password = await hasPassword(data.password);

  return User.create({ ...data, tenantId });
};
export const getUser = async (queryParams, tenantId) => {
  let filter = {
    tenantId: tenantId   // ✅ IMPORTANT
  };

  if (queryParams.userName) {
    filter.userName = {
      $regex: queryParams.userName,
      $options: "i",
    };
  }

  if (queryParams.contact_no) {
    filter.contact_no = {
      $regex: queryParams.contact_no,
      $options: "i",
    };
  }

  const users = await User.find(filter)
    .populate("role")
    .sort({ createdAt: -1 })
    .lean();

  return users;
};

export const getUserbyId = async (tenantId, id) => {
  return User.findById({ id, tenantId }) .populate({
      path: "role",
      populate: {
        path: "permissions",
      },
    });;
};

export const updateUser = async (tenantId, id, data) => {
  return User.findByIdAndUpdate({ id, tenantId }, data, { new: true });
};

export const deleteUser = async (tenantId, id) => {
  return User.findByIdAndDelete({ id, tenantId });
};


// auto generation tenent user for traial period
export const createTenantAdminUser = async ({
  tenantId,
  roleId,
  email,
  tenantName,
}) => {
  const plainPassword = generatePassword();
  const hashedPassword = await bcrypt.hash(plainPassword, 10);

  const user = await User.create({
    tenantId,
    userName: await generateUsername(tenantName),
    email,
    password: hashedPassword,
    role: roleId,
    isSuperAdmin: false,
  });

  return { user, plainPassword };
};

